### ISSUE TITLE
Team feedback

### ISSUE THREAD

**Issue by dvcorreia1984** [Ayokunnumi1/Portfolio-setup-and-mobile-first#5]
Good project Joy

These are some things you can give attention to: 

- When linking images that have spaces in their names, you can use double quotes "" to remove the CSS errors. It is better to use dashes "-" in stead of empty spaces in filenames.  
- You can use percentages to adjust your images sizes for background images. It is also possible to add more than one background image to an element. 

`.about {
  background-image: url(./Assets/illustration\ 2-about\ me\ mobile.svg), url(./Assets/Mask\ Group.svg);
  background-repeat: no-repeat;
  background-position: 0% 104%, 100% -12%;
}`

For the desktop version it is important to use a different

**Comment by donice** [comment]
You've done really well with this project, however, there are some aspects I'd suggest you geave an attention to, they are:

- The path to your contact background image isn't correct
